### ISSUE TITLE
add one click button deploy to heroku

### ISSUE THREAD

**Issue by mravinale** [MakingSense/WebApiCore-Seed#10]
https://devcenter.heroku.com/articles/heroku-button

**Comment by matiasbeckerle** [comment]
What's the idea & intentions behind this ticket @mravinale?

**Comment by mravinale** [comment]
Is part of a training for Gaston and provide simple deployment for our open source projects

**Comment by matiasbeckerle** [comment]
Hmm not sure I follow. You want to have this repository deployed & running live in Heroku?

**Comment by Dongata** [comment]
something like this [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/MakingSense/WebApiCore-Seed/tree/issue10-heroku-autodeploy)
but working :/

**Comment by matiasbeckerle** [comment]
@Dongata if this is not invasive let's go with it. Discussed informally with @mravinale and he told me some good arguments.
