### ISSUE TITLE
Remove SQL Server dependencies and use in-memory provider

### ISSUE THREAD

**Issue by matiasbeckerle** [MakingSense/WebApiCore-Seed#16]
I've seen we are including an SQL Server dependency `Microsoft.EntityFrameworkCore.SqlServer`. We should not require a provider like that one for a startup project. If we need storage capabilities here, let's go for an in-memory provider.

**Comment by Dongata** [comment]
## 🅱️ ackground
In the context that this is a seeder project, isn't a good practice add implementations, so, sql server implementation must go.
  
## Changes done
* Removes an unnecessary factory
* Changes the packages needed
* Changes the dbcontext configuration
   
## Notes  
Sorry guy that created the factory, was lovely and will be remembered.
 
## Demo
![works](https://user-images.githubusercontent.com/7729931/39945480-faa90662-5540-11e8-8813-8e4fd4a8c75d.gif)
