### ISSUE TITLE
Rename solution/projects

### ISSUE THREAD

**Issue by matiasbeckerle** [MakingSense/WebApiCore-Seed#23]
Solution/projects first part of the name is waaay long. Consider renaming it to something like just `Seed` or `StarterApp`.

At the end, solution should look like `Seed.sln`. Projects like:

```
Seed.Api
Seed.Domain
...
```

**Comment by Dongata** [comment]
Only proyects and sln, should the folders maintain the same name?

**Comment by matiasbeckerle** [comment]
I think it should too, yes. Thanks @Dongata!
