### ISSUE TITLE
Implement a gzip/deflate for large responses

### ISSUE THREAD

**Issue by Dongata** [MakingSense/WebApiCore-Seed#31]

**Comment by andresmoschini** [comment]
> Implement a gzip/deflate **for large responses**

Why not for all of them?

**Comment by Dongata** [comment]
because doesn't make sense to compress something that enters on a single [MTU](https://en.wikipedia.org/wiki/Maximum_transmission_unit), it is a waste of resources

**Comment by andresmoschini** [comment]
Thanks for your response! In that case, I guess that .NET Core GZIP middlewares should take that into account.

**Comment by andresmoschini** [comment]
It seems that maybe it is not a good idea to do it using .NET middlewares, see [this article in Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression)

**Comment by Dongata** [comment]
Thanks for share, the compression should be a hosting responsibility, that is out of the scope for a seeder API, putting this on wontfix. Thank you again dude.

**Comment by andresmoschini** [comment]
👍
