### ISSUE TITLE
Enable a free CI

### ISSUE THREAD

**Issue by andresmoschini** [MakingSense/WebApiCore-Seed#5]
I know that there are always things to do, so, it is only a suggestion.

It is very easy to configure a free CI service, for example we are already using [AppVeyor](https://www.appveyor.com/) for other .NET projects like [Documentation Middleware](https://github.com/MakingSense/aspnet-documentation-middleware). 

It is great because it could run the tests automatically, and in case that the project is a library it can create and publish the nuget packages.

Since you are using ASP.NET Core with .NET Core, you have more free options, for example, Travis CI (if I am not wrong).

PS. Nice initiative with the seed!

**Comment by Dongata** [comment]
Closes with
#11

**Comment by Dongata** [comment]
Closed with #12
